DEFAULT_SCHEMA = "https://"
DEFAULT_HOST = "xiaodu.baidu.com"

DEFAULT_PAYLOAD_VERSION = 3

DEVICE_LIST_QUERY = "/saiya/smarthome/devicelist?from=h5_control&withscene=1&generalscene=3"
DEVICE_ACTION_QUERY = "/saiya/smarthome/directivesend?from=h5_control"

BDUSS_COOKIE_KEY = "BDUSS"

REQUEST_HEADER = "header"
REQUEST_HEADER_NAMESPACE = "namespace"
REQUEST_HEADER_NAME = "name"
PAYLOAD_VERSION = "payloadVersion"
REQUEST_PARAMETERS = "parameters"
PROXY_CONNECT_STATUS = "proxyConnectionStatus"
REQUEST_PAYLOAD = "payload"
APPLIANCE = "appliance"
CONTROL_REQUEST_NAMESPACE = "DuerOS.ConnectedHome.Control"
ATTRIBUTE = "attribute"
ATTRIBUTE_VALUE = "attributeValue"

ADDITIONAL_COOKIES = {"smarthome-curtain-device-detail-new": "1"}

STATUS = "status"
MSG = "msg"
LOGID = "logid"
DATA = "data"
APPLIANCES = "appliances"
BOT_NAME = "botName"
BOT_ID = "botId"
BOT_LOGO_URL = "botLogo"
APPLIANCE_ID = "applianceId"
APPLIANCE_TYPES = "applianceTypes"
NICKNAMES = "nicknames"
DESCRIPTION = "friendlyDescription"
SUPPORTED_ACTIONS = "supportActions"
FRIENDLY_NAME = "friendlyName"
GROUP_NAME = "groupName"
ROOM_NAME = "roomName"
GROUP_ID = "groupId"
ROOM_ID = "roomId"
FLOOR_ID = "floorId"
FLOOR_NAME = "floorName"
ATTRIBUTES = "attributes"
CONNECTIVITY = "connectivity"
DETAIL = "detail"
NAME = "name"
RANGE = "range"
VALUE = "value"
TIMESTAMP_OF_SAMPLE = "timestampOfSample"
STATE_SETTING = "stateSetting"
TIME = "time"
TURN_ON_STATE = "turnOnState"
BRIGHTNESS = "brightness"
COLOR_TEMPERATURE_IN_KELVIN = "colorTemperatureInKelvin"
MODE = "mode"
ICON_URL = "icon"
BRIGHTNESS_AND_COLOR_TEMPERATURE = "brightnessAndColorTemperature"
BRIGHTNESS_AND_COLOR_TEMPERATURE_WITH_ICON = "brightnessAndColorTemperatureWithIcon"
ICON_URLS = "icons"
STATUS = "status"

STATUS_OK = 0

TURN_OFF_REQUEST = "TurnOffRequest"
TURN_ON_REQUEST = "TurnOnRequest"
SET_BRIGHTNESS_PERCENTAGE_REQUEST = "SetBrightnessPercentageRequest"
SET_COLOR_TEMPERATURE_REQUEST = "SetColorTemperatureRequest"